name: CI Pipeline
on:
  push:
  pull_request:
    branches:
      - main
      - develop

env:
  FIREFOX_BINARY_PATH: /opt/firefox-developer/firefox
  GECKODRIVER_BINARY_PATH: /usr/local/bin/geckodriver
  EXTENSION_PATH_GLOB: ./output/better_share_button-*.{xpi,zip}

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint and format
        run: |
          npm run lint
          npm run format

      - name: Install Firefox
        run: |
          wget -O firefox-developer.tar.bz2 "https://download-origin.cdn.mozilla.net/pub/devedition/releases/132.0b1/linux-x86_64/en-US/firefox-132.0b1.tar.bz2"
          tar -xjf firefox-developer.tar.bz2
          sudo mv firefox /opt/firefox-developer
          sudo ln -sf /opt/firefox-developer/firefox /usr/bin/firefox
          firefox --version

      - name: Install Geckodriver
        run: |
          GECKODRIVER_VERSION=v0.35.0
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test -- --testPathIgnorePatterns="test/integration/reddit.test.ts" --color --coverage

      - name: Upload code coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style: Auto-format code'
          branch: ${{ github.head_ref }}
