name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release name'
        required: true
      release_description:
        description: 'Description of the release'
        required: false

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts from CI pipeline
        uses: actions/download-artifact@v3
        with:
          name: build_artifact

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_description }}
          draft: false
          prerelease: false

      - name: Upload assets to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/better_share_button-*.zip
          asset_name: better_share_button.zip
          asset_content_type: application/zip
